version: '3.8'

services:
  frontend:
    build:
      context: ./app
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./api
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/test
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo_data:
