version: '3.8'

services:
  frontend:
    build:
      context: ./app
    networks:
      - mynet
    ports:
      - "3000:3000"
    environment:
      - API_URL=http://backend:3001
    depends_on:
      - backend

  backend:
    build:
      context: ./api
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/koywe
    networks:
      - mynet
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - mynet

volumes:
  mongo_data:

networks:
  mynet:
    driver: bridge